#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-$(pwd)}"
ROOT="$(cd "$ROOT" && pwd -P)"
PYTHON_BIN="${PYTHON_BIN:-python3}"
WORK="${TMPDIR:-/tmp}/sage-hermes-native-smoke-$$"
PROJECT="$WORK/project"
DEFAULT_PROJECT="$WORK/default-project"
HERMES_HOME_SMOKE="$WORK/hermes-home"
DEFAULT_HOME_SMOKE="$WORK/default-home"
PROFILE_HOME_SMOKE="$WORK/profile-home"
HOME_SMOKE="$WORK/home"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

[ -f "$ROOT/bin/sage" ] || fail "missing bin/sage under $ROOT"
[ -d "$ROOT/runtime/platforms/hermes" ] || fail "missing runtime/platforms/hermes"
[ ! -d "$ROOT/runtime/platforms/hermes/.claude-plugin" ] || fail "Hermes adapter must not contain .claude-plugin"
[ -f "$ROOT/runtime/platforms/hermes/setup/generate-hermes.sh" ] || fail "missing generate-hermes.sh"
[ -f "$ROOT/runtime/platforms/hermes/plugin-template/__init__.py" ] || fail "missing Hermes plugin __init__.py"
if grep -q '^hooks_auto_accept: true' "$ROOT/runtime/platforms/hermes/setup/generate-hermes.sh"; then
  fail "generator contains a broad hook auto-accept fallback"
fi

rm -rf "$WORK"
mkdir -p "$PROJECT" "$DEFAULT_PROJECT" "$HERMES_HOME_SMOKE" "$DEFAULT_HOME_SMOKE" "$PROFILE_HOME_SMOKE" "$HOME_SMOKE"
git init -q "$PROJECT"
cat > "$HERMES_HOME_SMOKE/constitution.md" <<'YAML'
---
name: smoke-hermes
tier: 2
extends: opensource
---

# Constitution - smoke Hermes profile

## Project Additions

(none)
YAML
cat > "$HERMES_HOME_SMOKE/config.yaml" <<'YAML'
platform_toolsets:
  cli: [hermes-cli, kanban]
  acp: [hermes-acp, kanban]
kanban:
  dispatch_in_gateway: true
  orchestrator_profile: planning-profile
YAML
cat > "$PROJECT/AGENTS.md" <<'MARKERLESS'
# Existing Project Instructions

Keep this prefix.

# Sage — Project Instructions

> Auto-generated by an older Sage adapter.

## Project State

- `.sage/work/` — old generated state guidance
- `gates/` — quality gate scripts and activation config

# User-Owned Suffix

Keep this suffix too.
MARKERLESS

(
  cd "$PROJECT"
  HOME="$HOME_SMOKE" HERMES_HOME="$HERMES_HOME_SMOKE" bash "$ROOT/bin/sage" init --platform hermes --no-memory
  HOME="$HOME_SMOKE" HERMES_HOME="$HERMES_HOME_SMOKE" bash "$ROOT/bin/sage" setup multi-agent --yes
)

[ -f "$PROJECT/AGENTS.md" ] || fail "AGENTS.md was not generated"
grep -q "Keep this prefix" "$PROJECT/AGENTS.md" || fail "AGENTS.md prefix was truncated"
grep -q "Keep this suffix too" "$PROJECT/AGENTS.md" || fail "AGENTS.md suffix was truncated"
if grep -q "older Sage adapter" "$PROJECT/AGENTS.md"; then
  fail "markerless legacy Sage block was not replaced"
fi
[ ! -d "$PROJECT/.claude" ] || fail ".claude must not be generated for Hermes"
[ -f "$PROJECT/.sage/config.yaml" ] || fail ".sage/config.yaml was not generated"
[ -f "$HERMES_HOME_SMOKE/plugins/sage/plugin.yaml" ] || fail "plugin.yaml was not installed"
[ -f "$HERMES_HOME_SMOKE/plugins/sage/__init__.py" ] || fail "__init__.py was not installed"
[ -f "$HERMES_HOME_SMOKE/plugins/sage/skills/build/SKILL.md" ] || fail "bundled build skill missing"
[ -f "$HERMES_HOME_SMOKE/plugins/sage/skills/autoresearch/SKILL.md" ] || fail "bundled autoresearch workflow missing"
[ -f "$HERMES_HOME_SMOKE/plugins/sage/skills/map/SKILL.md" ] || fail "bundled map workflow missing"
[ -f "$HERMES_HOME_SMOKE/skills/api/SKILL.md" ] || fail "top-level api skill missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-session-init.sh" ] || fail "session hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-mark-edit.sh" ] || fail "post_tool_call edit marker hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-pre-llm.py" ] || fail "advisory route hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-pre-tool.py" ] || fail "strict gate hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-learning-recall.py" ] || fail "learning recall hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-learning-observe.py" ] || fail "learning observer hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-reflect-checkpoint.py" ] || fail "reflection hook missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage_runtime/adapter.py" ] || fail "shared hook runtime missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage_runtime_cli.py" ] || fail "standalone runtime CLI missing"
[ ! -f "$HERMES_HOME_SMOKE/hooks/sage-inject.sh" ] || fail "legacy binding router was installed"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-screenshot.sh" ] || fail "screenshot helper missing"
[ -f "$HERMES_HOME_SMOKE/hooks/sage-verify.sh" ] || fail "verify gate missing"
[ -f "$HERMES_HOME_SMOKE/SOUL.md" ] || fail "profile SOUL.md missing"
[ -f "$HERMES_HOME_SMOKE/config.yaml" ] || fail "Hermes config.yaml missing"
[ -f "$PROJECT/.sage/runtime/route-catalog.json" ] || fail "validated route catalog missing"
[ -f "$PROJECT/.sage/composition.json" ] || fail "neutral composition catalog missing"
grep -q "Sage Profile Constitution" "$HERMES_HOME_SMOKE/SOUL.md" || fail "profile constitution missing from SOUL.md"
grep -q "opensource preset" "$HERMES_HOME_SMOKE/SOUL.md" || fail "opensource constitution preset missing from SOUL.md"
grep -q "enabled:" "$HERMES_HOME_SMOKE/config.yaml" || fail "plugins.enabled missing from config"
grep -q "sage" "$HERMES_HOME_SMOKE/config.yaml" || fail "sage not enabled in config"
grep -q "on_session_start" "$HERMES_HOME_SMOKE/config.yaml" || fail "on_session_start hook missing"
grep -q "pre_llm_call" "$HERMES_HOME_SMOKE/config.yaml" || fail "pre_llm_call hook missing"
grep -q "post_tool_call" "$HERMES_HOME_SMOKE/config.yaml" || fail "post_tool_call hook missing"
grep -q "sage-pre-llm.py" "$HERMES_HOME_SMOKE/config.yaml" || fail "advisory route hook not registered"
grep -q "sage-pre-tool.py" "$HERMES_HOME_SMOKE/config.yaml" || fail "strict gate hook not registered"
grep -q "sage-learning-recall.py" "$HERMES_HOME_SMOKE/config.yaml" || fail "learning recall hook not registered"
grep -q "sage-learning-observe.py" "$HERMES_HOME_SMOKE/config.yaml" || fail "learning observer hook not registered"
grep -q "sage-reflect-checkpoint.py" "$HERMES_HOME_SMOKE/config.yaml" || fail "reflection hook not registered"
if grep -q "sage-inject.sh" "$HERMES_HOME_SMOKE/config.yaml"; then
  fail "legacy binding router remains registered"
fi
grep -q "sage-mark-edit.sh" "$HERMES_HOME_SMOKE/config.yaml" || fail "sage-mark-edit.sh not registered"
grep -q "quick_commands:" "$HERMES_HOME_SMOKE/config.yaml" || fail "desktop quick_commands missing from config"
grep -q "sage-status:" "$HERMES_HOME_SMOKE/config.yaml" || fail "sage-status quick command missing from config"
grep -q "platform_toolsets:" "$HERMES_HOME_SMOKE/config.yaml" || fail "platform_toolsets missing from config"
grep -q "acp:" "$HERMES_HOME_SMOKE/config.yaml" || fail "ACP toolset config missing"
grep -q "hermes-acp" "$HERMES_HOME_SMOKE/config.yaml" || fail "Hermes ACP base toolset missing from config"
grep -q "sage" "$HERMES_HOME_SMOKE/config.yaml" || fail "sage toolset missing from config"
grep -q "delegation" "$HERMES_HOME_SMOKE/config.yaml" || fail "delegation toolset missing from config"
grep -q "kanban" "$HERMES_HOME_SMOKE/config.yaml" || fail "existing Kanban toolset/config was removed"
grep -q "orchestrator_profile: planning-profile" "$HERMES_HOME_SMOKE/config.yaml" || fail "existing Kanban orchestration was changed"
if grep -q "hooks_auto_accept: true" "$HERMES_HOME_SMOKE/config.yaml"; then
  fail "installer globally enabled unrelated shell hooks"
fi
[ -f "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" ] || fail "shell hook allowlist missing"
grep -q "sage-session-init.sh" "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" || fail "session hook not allowlisted"
grep -q "sage-mark-edit.sh" "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" || fail "mark-edit hook not allowlisted"
grep -q "sage-pre-llm.py" "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" || fail "advisory route hook not allowlisted"
grep -q "sage-learning-recall.py" "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" || fail "learning recall hook not allowlisted"
grep -q "sage-reflect-checkpoint.py" "$HERMES_HOME_SMOKE/shell-hooks-allowlist.json" || fail "reflection hook not allowlisted"

python3 - "$HERMES_HOME_SMOKE/plugins/sage" "$PROJECT" <<'PY'
import importlib.util
import json
import pathlib
import sys

plugin = pathlib.Path(sys.argv[1])
project = pathlib.Path(sys.argv[2])
spec = importlib.util.spec_from_file_location("sage_plugin_smoke", plugin / "__init__.py")
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)

class Context:
    def __init__(self):
        self.commands = {}
        self.skills = {}
        self.tools = {}
        self.builtins = {"status"}

    def register_command(self, name, handler, description="", args_hint=""):
        if name in self.builtins:
            return
        self.commands[name] = (handler, description, args_hint)

    def register_skill(self, name, path, description=""):
        self.skills[name] = (path, description)

    def register_tool(self, name, toolset, schema, handler, **kwargs):
        self.tools[name] = (toolset, schema, handler, kwargs)

ctx = Context()
module.register(ctx)
for name in [
    "sage", "build", "build-x", "fix", "architect", "review", "review-spec",
    "review-plan", "implement", "review-code", "autoresearch", "map", "sage-status",
]:
    if name not in ctx.commands:
        raise SystemExit(f"missing slash command: {name}")
if "status" in ctx.commands:
    raise SystemExit("Hermes plugin must not register conflicting /status")
if "build" not in ctx.skills:
    raise SystemExit("missing registered build skill")
for name in ["sage_spec_check", "sage_hallucination_check", "sage_verify", "sage_visual_gate", "sage_run_gates"]:
    if name not in ctx.tools:
        raise SystemExit(f"missing registered Sage tool: {name}")
if ctx.tools["sage_verify"][0] != "sage":
    raise SystemExit("Sage tools must register under the sage toolset")
gate_result = json.loads(ctx.tools["sage_run_gates"][2]({"mode": "fix", "cwd": str(project)}))
if not gate_result.get("ok"):
    raise SystemExit(f"sage_run_gates fix mode did not pass script checks: {gate_result}")
if gate_result.get("all_gates_complete"):
    raise SystemExit("sage_run_gates must require agent review after script checks")
if "hallucination-check" not in gate_result.get("active_gates", []):
    raise SystemExit("sage_run_gates did not activate hallucination-check for fix mode")
body = ctx.commands["build"][0]("")
if "Build Workflow" not in body:
    raise SystemExit("build command handler did not return workflow text")
if "sage_run_gates" not in body:
    raise SystemExit("build command handler did not include Hermes gate adapter note")
if "delegate_task" not in body:
    raise SystemExit("build command handler did not include Hermes delegate_task adapter note")
for phrase in (
    "Hermes execution topology",
    "synchronous",
    "durable",
    "HERMES_KANBAN_TASK",
    "kanban_complete",
    "kanban_block",
    "direct",
    "Do not create delegation or Kanban work automatically",
):
    if phrase not in ctx.commands["build-x"][0]("--kanban ship feature"):
        raise SystemExit(f"build command handler omitted native execution guidance: {phrase}")
review_body = ctx.commands["review"][0]("")
if "sub-agent" in review_body.lower() and "delegate_task" not in review_body:
    raise SystemExit("review command handler did not map sub-agent work to delegate_task")
PY

SESSION_OUT="$WORK/session-init.out"
printf '{"cwd":"%s","hook_event_name":"on_session_start","session_id":"smoke"}\n' "$PROJECT" \
  | bash "$HERMES_HOME_SMOKE/hooks/sage-session-init.sh" >"$SESSION_OUT"
python3 - "$SESSION_OUT" <<'PY'
import json
import sys
data = json.loads(open(sys.argv[1], encoding="utf-8").read())
if "Sage Context" not in data.get("context", ""):
    raise SystemExit("session hook did not emit JSON Sage Context")
PY

mkdir -p "$PROJECT/.sage/work/percent-title"
cat > "$PROJECT/.sage/work/percent-title/plan.md" <<'PLAN'
---
title: "Reduce latency by 50%"
status: in-progress
phase: implement
---
PLAN
PERCENT_OUT="$WORK/percent-session.json"
PERCENT_ERR="$WORK/percent-session.err"
printf '{"cwd":"%s","hook_event_name":"on_session_start","session_id":"smoke-2"}\n' "$PROJECT" \
  | bash "$HERMES_HOME_SMOKE/hooks/sage-session-init.sh" >"$PERCENT_OUT" 2>"$PERCENT_ERR"
grep -q 'Reduce latency by 50%' "$PERCENT_OUT" || fail "percent title was garbled"
if grep -q 'invalid conversion' "$PERCENT_ERR"; then
  fail "session hook interpreted a work title as a printf format"
fi
grep -q 'Another Sage session appears active' "$PERCENT_OUT" || fail "Hermes session collision guard is inert"

NODE_TEST="$WORK/node-path-test"
mkdir -p "$NODE_TEST/bin" "$NODE_TEST/project/node_modules" "$NODE_TEST/node_modules"
cat > "$NODE_TEST/bin/node" <<'NODE'
#!/usr/bin/env bash
if [ "${1:-}" = "-p" ]; then
  printf ':'
  exit 0
fi
if [ "${1:-}" = "-e" ]; then
  printf '%s' "${NODE_PATH:-}" > "$NODE_PATH_CAPTURE"
  exit 1
fi
exit 1
NODE
chmod +x "$NODE_TEST/bin/node"
(
  cd "$NODE_TEST/project"
  env -u NODE_PATH PATH="$NODE_TEST/bin:$PATH" NODE_PATH_CAPTURE="$NODE_TEST/captured" \
    bash "$ROOT/runtime/tools/sage-screenshot.sh" https://example.invalid >/dev/null 2>&1 || true
)
[ -s "$NODE_TEST/captured" ] || fail "screenshot helper did not export NODE_PATH"
grep -q ':' "$NODE_TEST/captured" || fail "screenshot helper ignored Node's path delimiter"
if grep -q ';' "$NODE_TEST/captured"; then
  fail "screenshot helper used a Windows delimiter for a POSIX Node runtime"
fi

MALFORMED_HOME="$WORK/malformed-home"
mkdir -p "$MALFORMED_HOME"
printf 'hooks: [unterminated\n' > "$MALFORMED_HOME/config.yaml"
if HOME="$HOME_SMOKE" HERMES_HOME="$MALFORMED_HOME" \
  bash "$PROJECT/sage/runtime/platforms/hermes/setup/generate-hermes.sh" "$PROJECT" \
  >/dev/null 2>&1; then
  fail "Hermes generator accepted malformed config"
fi
grep -q '^hooks: \[unterminated$' "$MALFORMED_HOME/config.yaml" || fail "malformed config was overwritten"
[ ! -d "$MALFORMED_HOME/plugins/sage" ] || fail "generator copied plugin before config preflight"
find "$MALFORMED_HOME" -name 'config.yaml.malformed-*.bak' -print -quit | grep -q . \
  || fail "malformed config backup missing"

INJECT_OUT="$WORK/sage-pre-llm.out"
printf '{"cwd":"%s","hook_event_name":"pre_llm_call","session_id":"smoke","extra":{"user_message":"map the repository"}}\n' "$PROJECT" \
  | "$PYTHON_BIN" "$HERMES_HOME_SMOKE/hooks/sage-pre-llm.py" >"$INJECT_OUT"
python3 - "$INJECT_OUT" <<'PY'
import json
import sys
data = json.loads(open(sys.argv[1], encoding="utf-8").read())
if "Sage advisory" not in data.get("context", ""):
    raise SystemExit("pre_llm_call hook did not emit bounded advisory routing")
PY

NON_SAGE_DIR="$WORK/non-sage"
mkdir -p "$NON_SAGE_DIR"
INJECT_FALLBACK_OUT="$WORK/sage-pre-llm-fallback.out"
printf '{"cwd":"%s","hook_event_name":"pre_llm_call","session_id":"smoke","extra":{"user_message":"ordinary chat"}}\n' "$NON_SAGE_DIR" \
  | "$PYTHON_BIN" "$HERMES_HOME_SMOKE/hooks/sage-pre-llm.py" >"$INJECT_FALLBACK_OUT"
python3 - "$INJECT_FALLBACK_OUT" <<'PY'
import json
import sys
data = json.loads(open(sys.argv[1], encoding="utf-8").read())
if data.get("context", ""):
    raise SystemExit("pre_llm_call fallback should be empty outside a Sage project")
PY

STANDALONE_PROJECT="$WORK/standalone-project"
mkdir -p "$STANDALONE_PROJECT/.sage/runtime"
cp "$PROJECT/.sage/runtime/route-catalog.json" "$STANDALONE_PROJECT/.sage/runtime/route-catalog.json"
STANDALONE_OUT="$WORK/sage-pre-llm-standalone.out"
(
  cd "$STANDALONE_PROJECT"
  printf '{"cwd":"%s","hook_event_name":"pre_llm_call","session_id":"standalone","extra":{"user_message":"map the repository"}}\n' "$STANDALONE_PROJECT" \
    | "$PYTHON_BIN" "$HERMES_HOME_SMOKE/hooks/sage-pre-llm.py" >"$STANDALONE_OUT"
)
python3 - "$STANDALONE_OUT" <<'PY'
import json
import sys
data = json.loads(open(sys.argv[1], encoding="utf-8").read())
if "Sage advisory" not in data.get("context", ""):
    raise SystemExit("standalone profile hook could not invoke bundled runtime CLI")
PY

printf '{"cwd":"%s","hook_event_name":"post_tool_call","session_id":"smoke","tool_name":"write_file"}\n' "$PROJECT" \
  | bash "$HERMES_HOME_SMOKE/hooks/sage-mark-edit.sh" >/dev/null
[ -f "$PROJECT/.sage/.last-edit" ] || fail "post_tool_call hook did not mark edit"

(
  cd "$DEFAULT_PROJECT"
  HOME="$DEFAULT_HOME_SMOKE" HERMES_HOME= bash "$ROOT/bin/sage" init --platform hermes --no-memory >/dev/null
)
[ -f "$DEFAULT_HOME_SMOKE/.hermes/plugins/sage/plugin.yaml" ] || fail "default ~/.hermes plugin install missing"
[ -f "$DEFAULT_HOME_SMOKE/.hermes/config.yaml" ] || fail "default ~/.hermes config missing"

HERMES_HOME="$PROFILE_HOME_SMOKE" bash "$DEFAULT_PROJECT/sage/runtime/platforms/hermes/setup/generate-hermes.sh" "$DEFAULT_PROJECT" >/dev/null
[ -f "$PROFILE_HOME_SMOKE/plugins/sage/plugin.yaml" ] || fail "profile Hermes plugin install missing"
[ -f "$PROFILE_HOME_SMOKE/config.yaml" ] || fail "profile Hermes config missing"
[ -f "$DEFAULT_HOME_SMOKE/.hermes/plugins/sage/plugin.yaml" ] || fail "default Hermes install was not preserved after profile install"

echo "PASS: Hermes native smoke"
