"""Sage Hermes plugin.

The plugin registers Sage workflow slash commands and exposes bundled Sage
skills as explicit plugin skills. Generated by `sage init --platform hermes`.
"""

from __future__ import annotations

import logging
import json
import os
import subprocess
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger(__name__)

PLUGIN_DIR = Path(__file__).resolve().parent
SKILLS_DIR = PLUGIN_DIR / "skills"
HERMES_HOME = PLUGIN_DIR.parent.parent
HOOKS_DIR = HERMES_HOME / "hooks"

SLASH_COMMAND_SKILLS = (
    ("sage", "sage"),
    ("build", "build"),
    ("fix", "fix"),
    ("architect", "architect"),
    ("analyze", "analyze"),
    ("learn", "learn"),
    ("map", "map"),
    ("qa", "qa"),
    ("reflect", "reflect"),
    ("research", "research"),
    ("review", "review"),
    # Hermes has a built-in /status command, so expose a guaranteed Sage name.
    ("sage-status", "status"),
    ("design", "design"),
    ("design-review", "design-review"),
    ("continue", "continue"),
    ("autoresearch", "autoresearch"),
)

HERMES_DELEGATION_NOTE = """

## Hermes Adapter: Sub-Agents

Whenever Sage says `Task tool`, `sub-agent`, `subagent`, `independent review`,
`auto-review`, `Gate 3`, or `Auto-QA`, use Hermes `delegate_task` when that
tool is available. Pass a self-contained context package: goal, relevant files,
spec/plan paths, changed-file list, test output, gate results, and exact review
criteria. If `delegate_task` is unavailable, follow Sage's canonical same-session
fallback.
"""

HERMES_GATE_TOOL_NOTE = """

## Hermes Adapter: Quality Gates

When this workflow reaches `quality-gates`, call the native `sage_run_gates` tool first.
Use `mode=fix`, `mode=build`, or `mode=architect` to match the current workflow.
For build/architect spec checks, pass `plan_file` and `task_number` when available.

`sage_run_gates` runs the script-first deterministic checks from `gate-modes.yaml`.
If it returns `agent_review_required`, complete those listed reviews before claiming
the gate sequence is complete. For Gate 3 and Auto-QA, call Hermes `delegate_task`
when that tool is available; otherwise follow Sage's canonical same-session fallback.
"""

SAGE_SPEC_CHECK_SCHEMA = {
    "name": "sage_spec_check",
    "description": "Run Sage Gate 1 spec compliance against a plan task.",
    "parameters": {
        "type": "object",
        "properties": {
            "plan_file": {"type": "string", "description": "Path to plan.md, relative to cwd or absolute."},
            "task_number": {"type": "integer", "description": "Task number from the plan to verify."},
            "cwd": {"type": "string", "description": "Optional project working directory."},
        },
        "required": ["plan_file", "task_number"],
    },
}

SAGE_HALLUCINATION_CHECK_SCHEMA = {
    "name": "sage_hallucination_check",
    "description": "Run Sage Gate 4 hallucination checks for imports, referenced files, and phantom APIs.",
    "parameters": {
        "type": "object",
        "properties": {
            "target": {"type": "string", "description": "File or directory to check. Defaults to current project."},
            "project_root": {"type": "string", "description": "Project root used for dependency checks. Defaults to cwd."},
            "cwd": {"type": "string", "description": "Optional project working directory."},
        },
    },
}

SAGE_VERIFY_SCHEMA = {
    "name": "sage_verify",
    "description": "Run Sage Gate 5 verification: tests, build checks, and clean-code marker checks.",
    "parameters": {
        "type": "object",
        "properties": {
            "project_root": {"type": "string", "description": "Project root to verify. Defaults to cwd."},
            "cwd": {"type": "string", "description": "Optional project working directory."},
        },
    },
}

SAGE_VISUAL_GATE_SCHEMA = {
    "name": "sage_visual_gate",
    "description": "Run Sage Gate 6 visual verification against a URL and capture screenshots.",
    "parameters": {
        "type": "object",
        "properties": {
            "url": {"type": "string", "description": "URL to capture, such as http://localhost:3000 or file:///..."},
            "output_dir": {"type": "string", "description": "Directory for screenshots. Defaults to .sage/screenshots."},
            "cwd": {"type": "string", "description": "Optional project working directory."},
        },
        "required": ["url"],
    },
}

SAGE_RUN_GATES_SCHEMA = {
    "name": "sage_run_gates",
    "description": (
        "Read Sage gate-modes.yaml for fix/build/architect and run the active "
        "Hermes-executable gate scripts in order. Returns the required agent-review "
        "follow-ups for gates that are not fully decidable by scripts."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "mode": {
                "type": "string",
                "enum": ["fix", "build", "architect"],
                "description": "Sage workflow mode whose gate policy should be applied.",
            },
            "plan_file": {"type": "string", "description": "Path to plan.md for spec-compliance."},
            "task_number": {"type": "integer", "description": "Plan task number for spec-compliance."},
            "target": {"type": "string", "description": "File or directory for hallucination-check."},
            "project_root": {"type": "string", "description": "Project root for hallucination/verification."},
            "visual_url": {"type": "string", "description": "URL for visual-verification; enables the visual gate when provided."},
            "visual_output_dir": {"type": "string", "description": "Screenshot output directory for visual-verification."},
            "optional_gates": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional gate names to run in addition to mandatory gates.",
            },
            "include_optional": {
                "type": "boolean",
                "description": "Run every optional gate listed for the selected mode.",
            },
            "cwd": {"type": "string", "description": "Optional project working directory."},
        },
        "required": ["mode"],
    },
}

DEFAULT_GATE_MODES = {
    "fix": {
        "mandatory": ["hallucination-check", "verification"],
        "optional": ["spec-compliance"],
        "skipped": ["constitution-compliance", "code-quality"],
    },
    "build": {
        "mandatory": ["spec-compliance", "constitution-compliance", "code-quality", "hallucination-check", "verification"],
        "optional": [],
        "skipped": [],
    },
    "architect": {
        "mandatory": ["spec-compliance", "constitution-compliance", "code-quality", "hallucination-check", "verification"],
        "optional": [],
        "skipped": [],
    },
}

GATE_ORDER = {
    "spec-compliance": 1,
    "constitution-compliance": 2,
    "code-quality": 3,
    "hallucination-check": 4,
    "verification": 5,
    "visual-verification": 6,
    "auto-qa": 8,
}

GATE_ALIASES = {
    "spec": "spec-compliance",
    "spec-check": "spec-compliance",
    "hallucination": "hallucination-check",
    "verify": "verification",
    "visual": "visual-verification",
    "visual-gate": "visual-verification",
    "visual-check": "visual-verification",
}

AGENT_REVIEW_GATES = {
    "constitution-compliance": "No script exists; review the active constitution and check each principle.",
    "code-quality": "No script exists; run the quality-review/code-quality gate. Use sub-agent delegation when Hermes exposes it.",
    "auto-qa": "Advisory Gate 8; run auto-qa when scope/config/tool availability activate it.",
}

SCRIPT_REVIEW_NOTES = {
    "spec-compliance": "Script passed; now perform adversarial spec review before considering Gate 1 complete.",
    "hallucination-check": "Script passed; now check for non-obvious hallucinations the script cannot catch.",
    "verification": "Script passed; now verify acceptance criteria and evidence beyond the test runner output.",
    "visual-verification": "Script passed; now review the captured screenshots for visual correctness if this is a UI change.",
}


def _skill_path(skill_id: str) -> Path:
    return SKILLS_DIR / skill_id / "SKILL.md"


def _read_skill_text(skill_id: str, raw_args: str = "") -> str:
    path = _skill_path(skill_id)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return f"Sage workflow file not found: {path}"
    except OSError as exc:
        return f"Could not read Sage workflow {skill_id}: {exc}"
    text = text.replace("$ARGUMENTS", raw_args or "")
    if _needs_delegation_note(text):
        text = f"{text.rstrip()}\n{HERMES_DELEGATION_NOTE}"
    if skill_id in {"build", "fix", "architect"}:
        text = f"{text.rstrip()}\n{HERMES_GATE_TOOL_NOTE}"
    return text


def _needs_delegation_note(text: str) -> bool:
    lowered = text.lower()
    triggers = (
        "task tool",
        "sub-agent",
        "subagent",
        "independent review",
        "auto-review",
        "auto-qa",
        "gate 3",
        "delegate",
    )
    return any(trigger in lowered for trigger in triggers)


def _read_skill_description(skill_id: str) -> Optional[str]:
    path = _skill_path(skill_id)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    frontmatter = text[3:end]
    in_description = False
    for line in frontmatter.splitlines():
        if line.startswith("description:"):
            value = line.split(":", 1)[1].strip().strip("'\"")
            if value in {">", ">-", "|", "|-"}:
                in_description = True
                continue
            return value or None
        if in_description:
            stripped = line.strip().strip("'\"")
            if stripped:
                return stripped
    return None


def _register_command(ctx, command_name: str, skill_id: str) -> None:
    def handler(raw_args: str = "") -> str:
        return _read_skill_text(skill_id, raw_args)

    description = _read_skill_description(skill_id) or f"Sage {skill_id} workflow"
    try:
        ctx.register_command(
            command_name,
            handler=handler,
            description=description,
        )
    except TypeError:
        ctx.register_command(command_name, handler, description)
    except Exception as exc:
        logger.debug("Could not register /%s: %s", command_name, exc)


def _cwd_from_args(args: dict) -> str:
    raw = str(args.get("cwd") or os.environ.get("TERMINAL_CWD") or os.getcwd()).strip()
    return raw or os.getcwd()


def _run_script_data(script_name: str, argv: list[str], cwd: str, timeout: int = 300) -> dict:
    script = HOOKS_DIR / script_name
    if not script.exists():
        return {"ok": False, "error": f"Sage script not found: {script}", "script": script_name, "cwd": cwd}
    completed = subprocess.run(
        ["bash", script.as_posix(), *argv],
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    stdout = completed.stdout or ""
    stderr = completed.stderr or ""
    return {
        "ok": completed.returncode == 0,
        "exit_code": completed.returncode,
        "script": script_name,
        "cwd": cwd,
        "stdout": stdout[-20000:],
        "stderr": stderr[-8000:],
    }


def _run_script(script_name: str, argv: list[str], cwd: str, timeout: int = 300) -> str:
    return json.dumps(_run_script_data(script_name, argv, cwd, timeout))


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return data if isinstance(data, dict) else {}
    except Exception:
        return _parse_simple_gate_yaml(path.read_text(encoding="utf-8"))


def _parse_simple_gate_yaml(text: str) -> dict:
    data: dict[str, dict[str, list[str]]] = {}
    section: str | None = None
    key: str | None = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        stripped = line.strip()
        if indent == 0 and stripped.endswith(":"):
            section = stripped[:-1]
            data.setdefault(section, {})
            key = None
        elif indent == 2 and stripped.endswith(":") and section:
            key = stripped[:-1]
            data[section].setdefault(key, [])
        elif stripped.startswith("- ") and section and key:
            data[section].setdefault(key, []).append(stripped[2:].strip())
    return data


def _as_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        raw = value
    else:
        raw = [value]
    return [_canonical_gate(item) for item in raw if str(item).strip()]


def _canonical_gate(value) -> str:
    name = str(value).strip().lower().replace("_", "-")
    return GATE_ALIASES.get(name, name)


def _dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            out.append(item)
    return out


def _sort_gates(items: list[str]) -> list[str]:
    return sorted(_dedupe(items), key=lambda gate: (GATE_ORDER.get(gate, 99), gate))


def _gate_modes_path(cwd: str) -> Path:
    project_modes = Path(cwd) / ".sage" / "gates" / "gate-modes.yaml"
    if project_modes.exists():
        return project_modes
    return HOOKS_DIR / "gate-modes.yaml"


def _mode_config(cwd: str, mode: str) -> tuple[dict, dict]:
    source = _gate_modes_path(cwd)
    modes = _load_yaml(source)
    raw = modes.get(mode) if isinstance(modes, dict) else None
    if not isinstance(raw, dict):
        raw = DEFAULT_GATE_MODES.get(mode, {})
        source_label = "built-in fallback"
    else:
        source_label = str(source)

    config = {
        "mandatory": _as_list(raw.get("mandatory")),
        "optional": _as_list(raw.get("optional")),
        "skipped": _as_list(raw.get("skipped")),
    }
    meta = {
        "mode_config": source_label,
        "project_config": None,
        "waiver_required": [],
        "optional_enabled": [],
    }

    project_config = Path(cwd) / ".sage" / "config.yaml"
    project_data = _load_yaml(project_config)
    gates = project_data.get("gates") if isinstance(project_data, dict) else None
    if isinstance(gates, dict):
        meta["project_config"] = str(project_config)
        override = None
        if isinstance(gates.get("modes"), dict) and isinstance(gates["modes"].get(mode), dict):
            override = gates["modes"][mode]
        elif isinstance(gates.get(mode), dict):
            override = gates[mode]
        elif any(key in gates for key in ("mandatory", "optional", "skipped")):
            override = gates

        if isinstance(override, dict):
            for key in ("mandatory", "optional", "skipped"):
                if key in override:
                    config[key] = _as_list(override.get(key))

        disabled = _as_list(gates.get("disabled"))
        if disabled:
            original_mandatory = set(config["mandatory"])
            config["mandatory"] = [gate for gate in config["mandatory"] if gate not in disabled]
            config["optional"] = [gate for gate in config["optional"] if gate not in disabled]
            config["skipped"] = _dedupe(config["skipped"] + disabled)
            meta["waiver_required"] = sorted(original_mandatory.intersection(disabled))

        additional = _as_list(gates.get("additional"))
        if additional:
            config["optional"] = _dedupe(config["optional"] + additional)

        enabled_optional = (
            gates.get("enabled")
            or gates.get("optional_enabled")
            or gates.get("run_optional")
            or gates.get("enabled_optional")
        )
        meta["optional_enabled"] = _as_list(enabled_optional)

    for key in ("mandatory", "optional", "skipped"):
        config[key] = _sort_gates(config[key])
    return config, meta


def _gate_result(gate: str, required: str, status: str, blocking: bool, details: dict | None = None) -> dict:
    result = {
        "gate": gate,
        "required": required,
        "status": status,
        "blocking": blocking,
    }
    if details:
        result.update(details)
    return result


def _handle_sage_spec_check(args: dict, **_kwargs) -> str:
    plan_file = str(args.get("plan_file") or "").strip()
    task_number = str(args.get("task_number") or "").strip()
    if not plan_file or not task_number:
        return json.dumps({"ok": False, "error": "plan_file and task_number are required"})
    return _run_script("sage-spec-check.sh", [plan_file, task_number], _cwd_from_args(args))


def _handle_sage_hallucination_check(args: dict, **_kwargs) -> str:
    cwd = _cwd_from_args(args)
    target = str(args.get("target") or ".").strip()
    project_root = str(args.get("project_root") or ".").strip()
    return _run_script("sage-hallucination-check.sh", [target, project_root], cwd)


def _handle_sage_verify(args: dict, **_kwargs) -> str:
    cwd = _cwd_from_args(args)
    project_root = str(args.get("project_root") or ".").strip()
    return _run_script("sage-verify.sh", [project_root], cwd, timeout=600)


def _handle_sage_visual_gate(args: dict, **_kwargs) -> str:
    url = str(args.get("url") or "").strip()
    if not url:
        return json.dumps({"ok": False, "error": "url is required"})
    output_dir = str(args.get("output_dir") or ".sage/screenshots").strip()
    return _run_script("sage-visual-gate.sh", [url, output_dir], _cwd_from_args(args), timeout=600)


def _run_one_gate(gate: str, required: str, args: dict, cwd: str) -> dict:
    is_mandatory = required == "mandatory"

    if gate == "spec-compliance":
        plan_file = str(args.get("plan_file") or "").strip()
        task_number = str(args.get("task_number") or "").strip()
        if not plan_file or not task_number:
            return _gate_result(
                gate,
                required,
                "missing_args",
                is_mandatory,
                {"error": "plan_file and task_number are required for spec-compliance"},
            )
        data = _run_script_data("sage-spec-check.sh", [plan_file, task_number], cwd)
    elif gate == "hallucination-check":
        target = str(args.get("target") or ".").strip()
        project_root = str(args.get("project_root") or ".").strip()
        data = _run_script_data("sage-hallucination-check.sh", [target, project_root], cwd)
    elif gate == "verification":
        project_root = str(args.get("project_root") or ".").strip()
        data = _run_script_data("sage-verify.sh", [project_root], cwd, timeout=600)
    elif gate == "visual-verification":
        url = str(args.get("visual_url") or args.get("url") or "").strip()
        if not url:
            return _gate_result(
                gate,
                required,
                "missing_args",
                is_mandatory,
                {"error": "visual_url is required for visual-verification"},
            )
        output_dir = str(args.get("visual_output_dir") or args.get("output_dir") or ".sage/screenshots").strip()
        data = _run_script_data("sage-visual-gate.sh", [url, output_dir], cwd, timeout=600)
    elif gate in AGENT_REVIEW_GATES:
        return _gate_result(
            gate,
            required,
            "agent_review_required",
            False,
            {"agent_review_required": True, "note": AGENT_REVIEW_GATES[gate]},
        )
    else:
        return _gate_result(gate, required, "unsupported", is_mandatory, {"error": "No Hermes gate implementation registered"})

    return _gate_result(
        gate,
        required,
        "script_passed" if data.get("ok") else "failed",
        is_mandatory and not data.get("ok"),
        {
            **data,
            "agent_review_required": bool(data.get("ok")),
            "review_note": SCRIPT_REVIEW_NOTES.get(gate),
        },
    )


def _handle_sage_run_gates(args: dict, **_kwargs) -> str:
    mode = _canonical_gate(args.get("mode") or "")
    if mode not in DEFAULT_GATE_MODES:
        return json.dumps({"ok": False, "error": "mode must be one of: fix, build, architect"})

    cwd = _cwd_from_args(args)
    config, meta = _mode_config(cwd, mode)
    optional_requested = set(_as_list(args.get("optional_gates")))
    optional_requested.update(meta.get("optional_enabled", []))
    include_optional = bool(args.get("include_optional"))

    mandatory = config["mandatory"]
    optional = config["optional"]
    skipped = set(config["skipped"])
    active_optional = [
        gate for gate in optional
        if include_optional or gate in optional_requested
    ]
    visual_url = str(args.get("visual_url") or args.get("url") or "").strip()
    if visual_url and "visual-verification" not in skipped:
        active_optional.append("visual-verification")

    active = _sort_gates([gate for gate in mandatory + active_optional if gate not in skipped])
    required_by_gate = {gate: "mandatory" for gate in mandatory if gate not in skipped}
    for gate in active_optional:
        if gate not in required_by_gate:
            required_by_gate[gate] = "optional"

    results = [_run_one_gate(gate, required_by_gate.get(gate, "optional"), args, cwd) for gate in active]
    optional_not_run = _sort_gates([
        gate for gate in optional
        if gate not in skipped and gate not in active
    ])
    blocking = [result for result in results if result.get("blocking")]
    review_required = [result for result in results if result.get("agent_review_required")]
    waiver_required = meta.get("waiver_required") or []
    ok = not blocking and not waiver_required

    return json.dumps({
        "ok": ok,
        "all_gates_complete": ok and not review_required,
        "mode": mode,
        "cwd": cwd,
        "config": config,
        "sources": meta,
        "active_gates": active,
        "optional_not_run": optional_not_run,
        "skipped": _sort_gates(list(skipped)),
        "waiver_required": waiver_required,
        "agent_review_required": [
            {
                "gate": result.get("gate"),
                "required": result.get("required"),
                "note": result.get("review_note") or result.get("note"),
            }
            for result in review_required
        ],
        "results": results,
        "summary": {
            "script_passed": sum(1 for result in results if result.get("status") == "script_passed"),
            "failed": sum(1 for result in results if result.get("status") == "failed"),
            "agent_review_required": len(review_required),
            "missing_args": sum(1 for result in results if result.get("status") == "missing_args"),
            "unsupported": sum(1 for result in results if result.get("status") == "unsupported"),
            "blocking": len(blocking) + len(waiver_required),
        },
    })


SAGE_TOOLS: tuple[tuple[str, dict, Callable, str], ...] = (
    ("sage_spec_check", SAGE_SPEC_CHECK_SCHEMA, _handle_sage_spec_check, "S"),
    ("sage_hallucination_check", SAGE_HALLUCINATION_CHECK_SCHEMA, _handle_sage_hallucination_check, "S"),
    ("sage_verify", SAGE_VERIFY_SCHEMA, _handle_sage_verify, "S"),
    ("sage_visual_gate", SAGE_VISUAL_GATE_SCHEMA, _handle_sage_visual_gate, "S"),
    ("sage_run_gates", SAGE_RUN_GATES_SCHEMA, _handle_sage_run_gates, "S"),
)


def register(ctx) -> None:
    """Hermes plugin entry point."""
    if not SKILLS_DIR.is_dir():
        logger.warning("Sage skills directory not found: %s", SKILLS_DIR)
        return

    for child in sorted(SKILLS_DIR.iterdir()):
        skill_md = child / "SKILL.md"
        if not child.is_dir() or not skill_md.exists():
            continue
        try:
            ctx.register_skill(child.name, skill_md)
        except Exception as exc:
            logger.debug("Could not register skill %s: %s", child.name, exc)

    for command_name, skill_id in SLASH_COMMAND_SKILLS:
        if not _skill_path(skill_id).exists():
            continue
        _register_command(ctx, command_name, skill_id)

    for tool_name, schema, handler, emoji in SAGE_TOOLS:
        try:
            ctx.register_tool(
                name=tool_name,
                toolset="sage",
                schema=schema,
                handler=handler,
                emoji=emoji,
            )
        except Exception as exc:
            logger.debug("Could not register tool %s: %s", tool_name, exc)
