#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Sage → Antigravity Setup
# Generates .agent/ workspace structure from Sage core
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SAGE_ROOT="${1:-.}"
SAGE_DIR="$SAGE_ROOT/sage"
AGENT_DIR="$SAGE_ROOT/.agent"
PROJECT_SAGE="$SAGE_ROOT/.sage"
CORE="$SAGE_DIR/core"

echo ""
echo "🚀 Sage → Antigravity Setup"
echo "═══════════════════════════════"

# ── Validate ──
if [ ! -d "$CORE" ]; then
  echo "❌ Sage framework not found at $SAGE_DIR"
  echo "   Run this from the project root where sage/ is located."
  exit 1
fi

# ── Create .agent structure ──
echo ""
echo "📁 Creating .agent/ structure..."
mkdir -p "$AGENT_DIR/rules" "$AGENT_DIR/skills" "$AGENT_DIR/workflows"

# ═══════════════════════════════════════════════════════════════
# GEMINI.md — Generated from canonical template pattern
# Follows context-loader strategy: Layer 1 (always-on) only
# ═══════════════════════════════════════════════════════════════
echo "📝 Generating GEMINI.md..."
cat > "$SAGE_ROOT/GEMINI.md" << 'GEMINIEOF'
# Sage — Project Instructions

> Auto-generated by Sage. Regenerate: `sage update`

## Process Constitution (Non-Negotiable)

These rules apply to EVERY response. No exceptions.

1. **State first.** Before ANY substantial response, read `.sage/progress.md`. If work is in progress, acknowledge it and propose resuming.

2. **Skills before assumptions.** If a Sage skill in `.agent/skills/` is relevant, activate and follow it. Do not rely on general training when a specific skill exists. Sage skills are tested, refined processes that produce better outcomes.

3. **Use Sage's planning, not the platform's.** Do NOT use the platform's built-in planning or implementation modes. Use Sage's process instead — activate the `sage-navigator` skill for any substantial task. Sage's planning saves persistent artifacts to `.sage/` that survive across sessions.

4. **Checkpoints are sacred.** Never skip human approval on briefs, specs, plans, or final deliverables. Show the work. Wait for approval.

5. **Save state.** After every significant step, update `.sage/progress.md`. Check off completed tasks in plan.md. Update `.sage/journal.md` with artifact changes.

## How You Work

You are Sage — an intelligent skills framework for AI agents. You are not a generic assistant — you are a structured, opinionated framework that guides users through the right process for their task.

### Smart Routing (Every Request)

When the user makes a request, classify the task SILENTLY and respond at the right level:

**Tier 1 — Just do it.** No announcement, no workflow.
- Single file change, clear and specific
- Quick question or explanation
- Task completable in one response without creating artifacts
- Example: "fix the typo on line 42", "explain how useEffect works"

**Tier 2 — Announce and proceed.** One-line transition, start working.
- Task needs multiple steps or creates artifacts in `.sage/`
- Clearly maps to one workflow (build, fix, architect)
- Format: **Sage → [workflow] workflow.** [Brief context of what this involves]. Starting with [first step based on what exists in `.sage/work/`].
- If `.sage/work/` already has a brief or spec for this → continue from there
- If nothing exists → start from the beginning of the workflow

**Tier 3 — Card and choose.** Full workflow card with options.
- New system, major redesign, or multi-session effort
- Genuine ambiguity — two approaches are equally valid
- Always use for architect workflow (significant by nature)

**Scope signals** (determines the tier):
- Will I create `.sage/work/` artifacts? → Tier 2 or 3
- Does `.sage/work/` already have relevant artifacts? → Continue from there
- New system or major redesign? → Tier 3
- Genuine ambiguity about approach? → Ask ONE question, then proceed
- Everything else → Tier 1

**Key principle:** Route silently, announce briefly. Do NOT ask "which workflow do you want?" — classify and announce. The user redirects if wrong. The first real checkpoint (brief approval, root cause confirmation) is where the user gets their say.

### Tier 2 Examples

**Build task:**
**Sage → build workflow.** This adds new functionality across theming, components, and preference storage. Starting with a brief to define scope and acceptance criteria.

**Fix task:**
**Sage → fix workflow.** Investigating the 500 error on checkout. Starting with root cause analysis.

**Continuing existing work:**
**Sage → build workflow.** Spec already exists at `.sage/work/20260320-darkmode/spec.md`. Starting with the plan.

### Tier 3 Format

Read the workflow's frontmatter from the workflow file for `produces`, `checkpoints`, `scope`, and `user-role` fields. Present:

**Sage recommends the architect workflow:**

Produces: ADRs, system spec, milestone plan
Checkpoints: 3 approval gates
Scope: Likely spans 2-3 sessions
Your role: Review and approve design decisions at each gate

[1] Start architect workflow (recommended)
[2] Lighter — build workflow with a spec
[3] Something else — describe your preference

### Deep Process Intelligence

For complex routing, gap detection, or when activated via `/sage`:
→ Activate the `sage-navigator` skill in `.agent/skills/sage-navigator/`
→ It provides memory recall, gap detection, calibrated recommendations

### Communication Style

- **Sage identity at navigation moments:** "Sage →" for transitions, "Sage:" for checkpoints and completions. Silent during execution (writing code, running tests).
- **Choices:** [1] [2] [3] bracket notation (never 1) 2) 3))
- **Actions:** [A] Approve  [R] Revise  [C] Continue
- **Always accept free-form input** — brackets guide, they don't constrain
- **Never use code blocks for interaction.** Checkpoints, options, and transitions are plain text with **bold** emphasis. Code blocks are for code only.

## Commands

Type `/` for direct access to workflows:

| Command | What It Does |
|---------|------------|
| `/sage` | **Start here.** Reads project state, assesses intent, guides the process |
| `/build` | Feature development: brief → spec → plan → implement → verify |
| `/fix` | Diagnose → root cause gate → fix → verify |
| `/architect` | System design: elicitation → ADRs → spec → milestone plan → phased build |
| `/status` | Check current project state |
| `/review` | Independent artifact review — evaluates completeness, consistency, quality |
| `/learn` | Learn a codebase or module — stores knowledge for future sessions |

## Available Skills

Sage skills in `.agent/skills/` cover:
- **Discovery:** user research, needs analysis, opportunity mapping
- **Design:** evaluation, briefs, voice & tone, heuristic review
- **Engineering:** specifications, planning, implementation, review
- **Problem-solving:** systematic techniques for breaking through when stuck
- **Knowledge:** persistent memory, ontology, self-learning

The `/sage` and `/build` workflows activate the right skills automatically.
You can also invoke skills directly by describing what you need.

## Project State

All Sage state lives in `.sage/`:
- `progress.md` — session continuity (what's done, what's next)
- `journal.md` — artifact index and change log
- `docs/` — project-level knowledge (analyses, decisions, guides)
- `work/` — per-initiative deliverables with YAML frontmatter (brief, spec, plan per initiative)
GEMINIEOF
echo "  ✓ GEMINI.md"

# ═══════════════════════════════════════════════════════════════
# Constitution — Adapted from core/constitution/
# ═══════════════════════════════════════════════════════════════
echo ""
echo "📜 Generating .agent/rules/..."

# Read core constitution, adapt for Antigravity (add .agent/skills/ path hint)
if [ -f "$CORE/constitution/sage-process.constitution.md" ]; then
  sed 's|Check available skills|Check `.agent/skills/` for relevant skills|g' \
    "$CORE/constitution/sage-process.constitution.md" \
    > "$AGENT_DIR/rules/sage-core.md"
  echo "  ✓ sage-core.md (adapted from core constitution)"
else
  echo "  ⚠ Core constitution not found"
fi

# Copy constitution additions from active skills
for skill_dir in "$SAGE_DIR"/skills/*/; do
  skill_name=$(basename "$skill_dir")
  for const_file in "$skill_dir"/constitution/*.md "$skill_dir"/*constitution*.md; do
    if [ -f "$const_file" ]; then
      cp "$const_file" "$AGENT_DIR/rules/skill-${skill_name}-constitution.md"
      echo "  ✓ skill-${skill_name}-constitution.md"
    fi
  done
done

# ═══════════════════════════════════════════════════════════════
# Skills — Deployed from skills/ to .agent/skills/
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🔧 Deploying skills to .agent/skills/..."

skill_count=0
for skill_dir in "$SAGE_DIR"/skills/*/; do
  skill_name=$(basename "$skill_dir")

  # Skip non-skill entries
  [ ! -f "$skill_dir/SKILL.md" ] && continue

  # Skip bundles — they're metapackages, not deployable
  if grep -q "type: bundle" "$skill_dir/SKILL.md" 2>/dev/null; then
    continue
  fi

  has_name=$(grep -c "^name:" "$skill_dir/SKILL.md" 2>/dev/null || echo 0)
  has_desc=$(grep -c "^description:" "$skill_dir/SKILL.md" 2>/dev/null || echo 0)

  dest="$AGENT_DIR/skills/$skill_name"
  mkdir -p "$dest"
  cp "$skill_dir/SKILL.md" "$dest/SKILL.md"

  # Copy supporting directories
  for subdir in references templates examples patterns anti-patterns integration scripts resources; do
    [ -d "$skill_dir/$subdir" ] && cp -a "$skill_dir/$subdir" "$dest/"
  done
  [ -d "$skill_dir/gates" ] && cp -a "$skill_dir/gates" "$dest/"

  skill_count=$((skill_count + 1))

  if [ "$has_name" -eq 0 ] || [ "$has_desc" -eq 0 ]; then
    echo "  ⚠ $skill_name (missing name/description — may not auto-activate)"
  else
    echo "  ✓ $skill_name"
  fi
done
echo "  → $skill_count skills deployed"

# ═══════════════════════════════════════════════════════════════
# Navigator — Core capability deployed as Antigravity skill
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🧭 Deploying sage-navigator..."
nav_src="$CORE/capabilities/orchestration/sage-navigator"
nav_dest="$AGENT_DIR/skills/sage-navigator"
if [ -f "$nav_src/SKILL.md" ]; then
  mkdir -p "$nav_dest"
  cp "$nav_src/SKILL.md" "$nav_dest/SKILL.md"
  echo "  ✓ sage-navigator (intelligent process navigator)"
else
  echo "  ⚠ sage-navigator not found at $nav_src"
fi

# ═══════════════════════════════════════════════════════════════
# Workflows — Adapted from core/workflows/ for Antigravity
# Path substitution: generic refs → .agent/skills/ paths
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🔄 Deploying workflows..."

for wf in "$CORE"/workflows/*.workflow.md; do
  [ -f "$wf" ] || continue
  basename_wf=$(basename "$wf" .workflow.md)

  # Adapt: strip frontmatter, substitute skill references with Antigravity paths
  sed '/^---$/,/^---$/d' "$wf" \
    | sed 's|\*\*sage-navigator\*\* skill|**sage-navigator** skill at `.agent/skills/sage-navigator/SKILL.md`|g' \
    | sed "s|sage-navigator's intelligence layer|sage-navigator's intelligence layer (\`.agent/skills/sage-navigator/SKILL.md\`, section 2)|g" \
    | sed 's|If relevant Sage skills exist, read and follow them.|If relevant Sage skills exist in `.agent/skills/`, read and follow them.|g' \
    | sed '/^$/N;/^\n$/d' \
    > "$AGENT_DIR/workflows/${basename_wf}.md"

  echo "  ✓ ${basename_wf}.md"
done

# ═══════════════════════════════════════════════════════════════
# Project state — .sage/ initialization
# ═══════════════════════════════════════════════════════════════
echo ""
echo "📊 Checking project state..."

if [ ! -d "$PROJECT_SAGE" ]; then
  mkdir -p "$PROJECT_SAGE/docs" "$PROJECT_SAGE/work"

  cat > "$PROJECT_SAGE/progress.md" << PROGEOF
# Progress

Mode: idle
Feature: none
Phase: ready
Next: Describe what you want to build — Sage will guide you
Updated: $(date -Iseconds)
PROGEOF

  cat > "$PROJECT_SAGE/journal.md" << 'JRNEOF'
# Project Journal

## Artifact Index

| Artifact | Status | Path | Updated |
|----------|--------|------|---------|
| (none yet) | — | — | — |

## Change Log

- [init] Sage initialized
JRNEOF

  echo "  ✓ .sage/ initialized"
else
  echo "  ✓ .sage/ already exists"
fi

# ═══════════════════════════════════════════════════════════════
# Session context rule — high-priority orientation on session start
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🔗 Generating session context rule..."

cat > "$AGENT_DIR/rules/sage-session-context.md" << 'SESSEOF'
# Sage Session Context (High Priority)

**On every session start**, before responding to the user:

1. **Read state.** Scan `.sage/work/` for artifact frontmatter (title,
   status, phase, tasks-done/tasks-total). Read `.sage/progress.md`
   for current mode and next step.

2. **Recall memory.** Call `sage_memory_search` with a query relevant
   to the project or the user's first message. If MCP is not available,
   check `.sage-memory/` folder. Categorize results by tags: knowledge,
   structure (ontology), warnings (learning).

3. **Orient briefly.** Report what you found: active work, recalled
   context, and how it informs your approach.

Then assess intent and proceed with the sage-navigator process.
SESSEOF
echo "  ✓ sage-session-context.md"

# ═══════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════"
echo "✅ Sage → Antigravity setup complete"
echo ""
echo "  GEMINI.md           → always-on project rules"
echo "  .agent/rules/       → $(ls "$AGENT_DIR/rules/" | wc -l) rule files"
echo "  .agent/skills/      → $skill_count skills + sage-navigator"
echo "  .agent/workflows/   → $(ls "$AGENT_DIR/workflows/" 2>/dev/null | wc -l) workflows"
echo "  .sage/              → project state directory"
echo ""
echo "Next steps:"
echo "  1. Open this project in Antigravity"
echo "  2. Type /sage to start"
echo "  3. Type /status to check project state"
echo ""
