#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Sage → Antigravity Setup
# Generates .agent/ workspace structure from Sage core
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SAGE_ROOT="${1:-.}"
SAGE_DIR="$SAGE_ROOT/sage"
AGENT_DIR="$SAGE_ROOT/.agent"
PROJECT_SAGE="$SAGE_ROOT/.sage"
CORE="$SAGE_DIR/core"

echo ""
echo "🚀 Sage → Antigravity Setup"
echo "═══════════════════════════════"

# ── Validate ──
if [ ! -d "$CORE" ]; then
  echo "❌ Sage framework not found at $SAGE_DIR"
  echo "   Run this from the project root where sage/ is located."
  exit 1
fi

# ── Create .agent structure ──
echo ""
echo "📁 Creating .agent/ structure..."
mkdir -p "$AGENT_DIR/rules" "$AGENT_DIR/skills" "$AGENT_DIR/workflows"

# ═══════════════════════════════════════════════════════════════
# GEMINI.md — Generated from canonical template pattern
# Follows context-loader strategy: Layer 1 (always-on) only
# ═══════════════════════════════════════════════════════════════
echo "📝 Generating GEMINI.md..."
cat > "$SAGE_ROOT/GEMINI.md" << 'GEMINIEOF'
# Sage — Project Instructions

> Auto-generated by Sage. Regenerate: `sage update`

## Process Constitution (Non-Negotiable)

These rules apply to EVERY response. No exceptions.

1. **State first.** Before ANY substantial response, read `.sage/progress.md`. If work is in progress, acknowledge it and propose resuming.

2. **Skills before assumptions.** If a Sage skill in `.agent/skills/` is relevant, activate and follow it. Do not rely on general training when a specific skill exists. Sage skills are tested, refined processes that produce better outcomes.

3. **Use Sage's planning, not the platform's.** Do NOT use the platform's built-in planning or implementation modes. Use Sage's process instead — activate the `sage-navigator` skill for any substantial task. Sage's planning saves persistent artifacts to `.sage/` that survive across sessions.

4. **Checkpoints are sacred.** Never skip human approval on briefs, specs, plans, or final deliverables. Show the work. Wait for approval.

5. **Save state.** After every significant step, update `.sage/progress.md`.

## How You Work

You are augmented by Sage — an intelligent skills framework for AI agents. Sage provides skills that cover the full spectrum from understanding users to shipping code.

**For ANY substantial request** (build, create, analyze, research, redesign, plan, fix, improve):
→ Activate the `sage-navigator` skill in `.agent/skills/sage-navigator/`
→ It will assess intent, detect gaps, and recommend the right workflow
→ Follow its process — it produces better outcomes than ad-hoc approaches

**For quick questions or simple tasks** (explain something, small edit, clarification):
→ Respond directly — not everything needs a workflow

## Commands

Type `/` for direct access to workflows:

| Command | When to Use |
|---------|------------|
| `/sage` | **Start here.** Sage reads project state, assesses your intent, and guides the process |
| `/build` | Build a feature — includes scope assessment, brief, spec, plan, and implementation |
| `/fix` | Fix a bug — reproduce, test, fix, verify |
| `/architect` | Design a system — deep elicitation, architecture, milestone planning |
| `/status` | Check what's been done and what's next |

## How to Communicate

At every step, make it easy for the user to respond:
- **Decision points:** Present 2-4 numbered options + a free-form escape.
- **Checkpoints:** Use `[A] Approve` / `[R] Revise` shortcuts.
- **Continuations:** Recommend the next step with `[C] Continue`.
Always accept free-form input — these patterns guide, they don't constrain.

## Available Skills

Sage skills in `.agent/skills/` cover discovery, design, and engineering.
The `/sage` and `/build` workflows activate the right skills automatically.
You can also invoke skills directly by describing what you need.

## Project State

All Sage state lives in `.sage/`:
- `progress.md` — session continuity (what's done, what's next)
- `journal.md` — artifact index and change log
- `docs/` — project-level knowledge (analyses, decisions, guides)
- `work/` — per-initiative deliverables (brief, spec, plan per initiative)
GEMINIEOF
echo "  ✓ GEMINI.md"

# ═══════════════════════════════════════════════════════════════
# Constitution — Adapted from core/constitution/
# ═══════════════════════════════════════════════════════════════
echo ""
echo "📜 Generating .agent/rules/..."

# Read core constitution, adapt for Antigravity (add .agent/skills/ path hint)
if [ -f "$CORE/constitution/sage-process.constitution.md" ]; then
  sed 's|Check available skills|Check `.agent/skills/` for relevant skills|g' \
    "$CORE/constitution/sage-process.constitution.md" \
    > "$AGENT_DIR/rules/sage-core.md"
  echo "  ✓ sage-core.md (adapted from core constitution)"
else
  echo "  ⚠ Core constitution not found"
fi

# Copy constitution additions from active skills
for skill_dir in "$SAGE_DIR"/skills/@sage/*/; do
  skill_name=$(basename "$skill_dir")
  for const_file in "$skill_dir"/constitution/*.md "$skill_dir"/*constitution*.md; do
    if [ -f "$const_file" ]; then
      cp "$const_file" "$AGENT_DIR/rules/skill-${skill_name}-constitution.md"
      echo "  ✓ skill-${skill_name}-constitution.md"
    fi
  done
done

# ═══════════════════════════════════════════════════════════════
# Skills — Deployed from skills/@sage/ to .agent/skills/
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🔧 Deploying skills to .agent/skills/..."

skill_count=0
for skill_dir in "$SAGE_DIR"/skills/@sage/*/; do
  skill_name=$(basename "$skill_dir")

  # Skip bundles — they're metapackages, not deployable
  if grep -q "type: bundle" "$skill_dir/SKILL.md" 2>/dev/null; then
    continue
  fi

  has_name=$(grep -c "^name:" "$skill_dir/SKILL.md" 2>/dev/null || echo 0)
  has_desc=$(grep -c "^description:" "$skill_dir/SKILL.md" 2>/dev/null || echo 0)

  dest="$AGENT_DIR/skills/$skill_name"
  mkdir -p "$dest"
  cp "$skill_dir/SKILL.md" "$dest/SKILL.md"

  # Copy supporting directories
  for subdir in references templates examples patterns anti-patterns integration scripts resources; do
    [ -d "$skill_dir/$subdir" ] && cp -a "$skill_dir/$subdir" "$dest/"
  done
  [ -d "$skill_dir/gates" ] && cp -a "$skill_dir/gates" "$dest/"

  skill_count=$((skill_count + 1))

  if [ "$has_name" -eq 0 ] || [ "$has_desc" -eq 0 ]; then
    echo "  ⚠ $skill_name (missing name/description — may not auto-activate)"
  else
    echo "  ✓ $skill_name"
  fi
done
echo "  → $skill_count skills deployed"

# ═══════════════════════════════════════════════════════════════
# Navigator — Core capability deployed as Antigravity skill
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🧭 Deploying sage-navigator..."
nav_src="$CORE/capabilities/orchestration/sage-navigator"
nav_dest="$AGENT_DIR/skills/sage-navigator"
if [ -f "$nav_src/SKILL.md" ]; then
  mkdir -p "$nav_dest"
  cp "$nav_src/SKILL.md" "$nav_dest/SKILL.md"
  echo "  ✓ sage-navigator (intelligent process navigator)"
else
  echo "  ⚠ sage-navigator not found at $nav_src"
fi

# ═══════════════════════════════════════════════════════════════
# Workflows — Adapted from core/workflows/ for Antigravity
# Path substitution: generic refs → .agent/skills/ paths
# ═══════════════════════════════════════════════════════════════
echo ""
echo "🔄 Deploying workflows..."

for wf in "$CORE"/workflows/*.workflow.md; do
  [ -f "$wf" ] || continue
  basename_wf=$(basename "$wf" .workflow.md)

  # Adapt: strip frontmatter, substitute skill references with Antigravity paths
  sed '/^---$/,/^---$/d' "$wf" \
    | sed 's|\*\*sage-navigator\*\* skill|**sage-navigator** skill at `.agent/skills/sage-navigator/SKILL.md`|g' \
    | sed "s|sage-navigator's intelligence layer|sage-navigator's intelligence layer (\`.agent/skills/sage-navigator/SKILL.md\`, section 2)|g" \
    | sed 's|If relevant Sage skills exist, read and follow them.|If relevant Sage skills exist in `.agent/skills/`, read and follow them.|g' \
    | sed '/^$/N;/^\n$/d' \
    > "$AGENT_DIR/workflows/${basename_wf}.md"

  echo "  ✓ ${basename_wf}.md"
done

# ═══════════════════════════════════════════════════════════════
# Project state — .sage/ initialization
# ═══════════════════════════════════════════════════════════════
echo ""
echo "📊 Checking project state..."

if [ ! -d "$PROJECT_SAGE" ]; then
  mkdir -p "$PROJECT_SAGE/docs" "$PROJECT_SAGE/work"

  cat > "$PROJECT_SAGE/progress.md" << PROGEOF
# Progress

Mode: idle
Feature: none
Phase: ready
Next: Describe what you want to build — Sage will guide you
Updated: $(date -Iseconds)
PROGEOF

  cat > "$PROJECT_SAGE/journal.md" << 'JRNEOF'
# Project Journal

## Artifact Index

| Artifact | Status | Path | Updated |
|----------|--------|------|---------|
| (none yet) | — | — | — |

## Change Log

- [init] Sage initialized
JRNEOF

  echo "  ✓ .sage/ initialized"
else
  echo "  ✓ .sage/ already exists"
fi

# ═══════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════"
echo "✅ Sage → Antigravity setup complete"
echo ""
echo "  GEMINI.md           → always-on project rules"
echo "  .agent/rules/       → $(ls "$AGENT_DIR/rules/" | wc -l) rule files"
echo "  .agent/skills/      → $skill_count skills + sage-navigator"
echo "  .agent/workflows/   → $(ls "$AGENT_DIR/workflows/" 2>/dev/null | wc -l) workflows"
echo "  .sage/              → project state directory"
echo ""
echo "Next steps:"
echo "  1. Open this project in Antigravity"
echo "  2. Type /sage to start"
echo "  3. Type /status to check project state"
echo ""
