#!/usr/bin/env python3
"""gen_truth_table.py — the platform support table, generated from the contract.

The README used to carry a hand-written table saying which platforms enforce
what. It said "Full — Task tool + spec-gate hook" for Claude Code and offered a
paragraph of prose for everyone else. It also referenced generate-plugin.sh, a
script that has been dead and broken for releases.

A hand-written table of enforcement claims is the pre-1.2.0 mistake in its
purest form: a claim, with no mechanism, in the most-read file in the repo. It
drifts the moment a platform changes, and nothing notices, because nothing is
watching it.

So it is generated — from the capability contracts, which are checked, and from
the conformance reports, which are dated. Hand-editing the table fails CI, the
same way hand-editing plugin-dist does.

Usage:
    gen_truth_table.py            # print the table
    gen_truth_table.py --write    # rewrite the block in README.md
    gen_truth_table.py --check    # fail if the committed block != generated
"""

import argparse
import pathlib
import re
import subprocess
import sys
import json

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
README = REPO_ROOT / "README.md"
REPORTS = REPO_ROOT / "develop" / "conformance" / "reports"

BEGIN = "<!-- BEGIN GENERATED: platform-truth-table -->"
END = "<!-- END GENERATED: platform-truth-table -->"

MARK = {True: "✅", "attested": "📝", False: "—"}


def contracts():
    out = subprocess.run(
        ["python3", str(REPO_ROOT / "runtime" / "tools" / "contract.py"), "--json"],
        capture_output=True, text=True, cwd=str(REPO_ROOT))
    if out.returncode != 0:
        raise SystemExit("contract.py --json failed:\n" + out.stderr)
    return json.loads(out.stdout)


def latest_report(name):
    if not REPORTS.is_dir():
        return None
    hits = sorted(REPORTS.glob("%s-*.md" % name))
    return hits[-1] if hits else None


def cell(v):
    if v is True:
        return MARK[True]
    if v == "attested":
        return MARK["attested"]
    return MARK[False]


def render():
    cs = sorted(contracts(), key=lambda c: (c["community"], c["name"] != "claude-code", c["name"]))

    lines = [
        BEGIN,
        "",
        "<!-- Generated by runtime/tools/gen_truth_table.py from the platform",
        "     capability contracts. Do not hand-edit: `gen_truth_table.py --check`",
        "     fails CI when this block and the contracts disagree. -->",
        "",
        "| Platform | Tier | Veto | Post-tool | Subagents | Skills | Commands | Conformance |",
        "|---|:--:|:--:|:--:|:--:|:--:|:--:|---|",
    ]

    for c in cs:
        caps = c["capabilities"]
        rpt = latest_report(c["name"])
        # The date, not "everything after the first hyphen" — `claude-code` and
        # `gemini-cli` have hyphens in their NAMES, and split("-", 1) turned their
        # report labels into "code-2026-07-12" and "cli-2026-07-12".
        date = re.search(r"(\d{4}-\d{2}-\d{2})$", rpt.stem).group(1) if rpt else None
        rpt_cell = ("[%s](%s)" % (date, rpt.relative_to(REPO_ROOT).as_posix())
                    if rpt else "*never run*")
        label = c["name"] + (" *(community)*" if c["community"] else "")
        lines.append("| %s | **%s** | %s | %s | %s | %s | %s | %s |" % (
            label,
            c["tier"] or "—",
            cell(caps.get("pre-tool-veto")),
            cell(caps.get("post-tool-events")),
            cell(caps.get("subagent-dispatch")),
            cell(caps.get("native-skill-discovery")),
            cell(caps.get("command-delivery")),
            rpt_cell,
        ))

    lines += [
        "",
        "✅ checked · 📝 attested (evidence + expiry) · — not available",
        "",
        "**Tier is derived, not declared** — `A` = veto ∧ post-tool ∧ subagents;",
        "`B` = veto ∧ context-injection; `C` = context-injection only.",
        "",
        "**`Veto` is the column that matters.** It is the answer to \"can a hook",
        "BLOCK an edit before it happens?\" Everything else is a convenience.",
        "Where it is `—`, Sage's rules are prose — and the v1.2.1 eval measured a",
        "framework whose rules were prose and found a behavioural delta of **zero**.",
        "That is what Tier C means, stated in the only terms that are honest.",
        "",
        "Contracts: [`runtime/platforms/CONTRACT.md`](runtime/platforms/CONTRACT.md) ·",
        "Porting: [`docs/porting-sage.md`](docs/porting-sage.md)",
        "",
        END,
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    table = render()

    if not (args.write or args.check):
        print(table)
        return 0

    text = README.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        if args.check:
            print("❌ FAIL — README has no generated truth-table block. Run "
                  "gen_truth_table.py --write.", file=sys.stderr)
            return 1
        print("❌ README has no %s / %s markers — add them first." % (BEGIN, END),
              file=sys.stderr)
        return 1

    current = text[text.index(BEGIN):text.index(END) + len(END)]

    if args.check:
        if current.strip() != table.strip():
            print("❌ FAIL — the README's platform table disagrees with the "
                  "capability contracts.\n", file=sys.stderr)
            print("  Somebody hand-edited a generated table, or a contract "
                  "changed and the table did not.\n"
                  "  Either way the README is now making a claim the contract "
                  "does not support — which is the\n"
                  "  exact failure this generator exists to prevent.\n\n"
                  "  Fix:  python3 runtime/tools/gen_truth_table.py --write",
                  file=sys.stderr)
            return 1
        print("OK — the README's platform table matches the contracts.")
        return 0

    README.write_text(text.replace(current, table), encoding="utf-8")
    print("OK — README platform table regenerated from the contracts.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
